# Your Website Title
title: Melvin Ch'ng

# Your Website URL
url: 'http://your-url.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Melvin Ch'ng
tagline: Software Developer, IoT, Reverse Engineering
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Full Stack Developer, IoT, Reverse Engineering
description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: you.email.email@gmail.com
website: melvinchng.github.io # do not add http://
linkedin: realmelvinchng
github: melvinchng
twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm